name: PyPI Deployment

on:
  release:
    types: [created]
    
env:
  POETRY_USERNAME: ${{ secrets.PYPI_API_USERNAME }}
  POETRY_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
  
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip poetry
          poetry install

      - name: Set Poetry config
        run: poetry config pypi-token.pypi ${{ secrets.PYPI_PROJECT_TOKEN }}

      - name: Publish package
        run: poetry publish --build
